import { DriverConfig } from "@/types";

export const drivers: DriverConfig[] = [
  {
    slug: "cpi",
    title: "CPI",
    shortTitle: "CPI",
    category: "Inflation",
    description: "Headline consumer inflation and its spillover into Fed expectations and the dollar.",
    frequency: "monthly",
    weight: 0.1,
    scoreMode: "inflation-index",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "CPIAUCSL",
      label: "Consumer Price Index for All Urban Consumers",
      sourceLabel: "FRED / BLS",
      sourceUrl: "https://fred.stlouisfed.org/series/CPIAUCSL",
      units: "Index",
    },
    narrative: {
      definition: "CPI measures the price level paid by urban consumers across a broad basket of goods and services.",
      whyItMatters: "Headline CPI sets the tone for inflation expectations and shapes how quickly the market believes the Fed can ease.",
      inflationImpact: "A firmer CPI trend suggests inflation pressure is still broad enough to delay a clean return to target.",
      growthImpact: "Hot inflation can initially reflect strong demand, but persistent pressure eventually erodes real income and slows activity.",
      fedTransmission: "If CPI stays sticky, the Fed is more likely to maintain restrictive policy or cut less aggressively than markets expect.",
      yieldDxyChain: "Hot CPI tends to lift policy expectations, support front-end yields, and improve the carry backdrop for DXY.",
      currentReadingLogic: "The page emphasizes the latest reading, the prior print, YoY inflation, and short-run annualized momentum.",
      scoringLogic: "The score rises when headline inflation remains elevated versus target and near-term momentum is not convincingly cooling.",
    },
  },
  {
    slug: "core-cpi",
    title: "Core CPI",
    shortTitle: "Core CPI",
    category: "Inflation",
    description: "Underlying consumer inflation excluding food and energy.",
    frequency: "monthly",
    weight: 0.11,
    scoreMode: "inflation-index",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "CPILFESL",
      label: "Consumer Price Index Less Food and Energy",
      sourceLabel: "FRED / BLS",
      sourceUrl: "https://fred.stlouisfed.org/series/CPILFESL",
      units: "Index",
    },
    narrative: {
      definition: "Core CPI strips out food and energy to isolate the stickier part of consumer inflation.",
      whyItMatters: "Core CPI is one of the cleanest gauges of underlying inflation persistence and is central to rates pricing.",
      inflationImpact: "Sticky core inflation signals that disinflation is incomplete and that price pressure is not just commodity noise.",
      growthImpact: "If core inflation stays firm, tighter real financial conditions can weigh on growth later in the cycle.",
      fedTransmission: "A stubborn core CPI trend tends to keep the Fed cautious on cuts and reinforces a higher-for-longer stance.",
      yieldDxyChain: "Sticky core inflation tends to push real and nominal yields higher, which is usually supportive for the dollar.",
      currentReadingLogic: "The framework compares the latest print to prior readings, YoY inflation, and the recent annualized run rate.",
      scoringLogic: "The score rises when core inflation remains well above comfort and recent momentum is not normalizing fast enough.",
    },
  },
  {
    slug: "ppi",
    title: "PPI",
    shortTitle: "PPI",
    category: "Inflation",
    description: "Producer-level inflation and upstream price pressure.",
    frequency: "monthly",
    weight: 0.07,
    scoreMode: "inflation-index",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "PPIACO",
      label: "Producer Price Index by Commodity for All Commodities",
      sourceLabel: "FRED / BLS",
      sourceUrl: "https://fred.stlouisfed.org/series/PPIACO",
      units: "Index",
    },
    narrative: {
      definition: "PPI tracks prices received by domestic producers, offering a read on pipeline inflation.",
      whyItMatters: "Producer prices can foreshadow pressure that later feeds through to consumers, margins, and policy expectations.",
      inflationImpact: "Rising PPI suggests upstream pricing pressure remains alive even if consumer inflation has cooled temporarily.",
      growthImpact: "Persistent input-cost pressure can squeeze margins and slow investment if demand softens.",
      fedTransmission: "A stronger PPI trend can make the Fed more hesitant to lean dovish before downstream disinflation is secured.",
      yieldDxyChain: "Firm producer inflation can keep yields supported through hawkish repricing and indirectly help DXY.",
      currentReadingLogic: "The signal focuses on annual inflation and recent short-run momentum.",
      scoringLogic: "The score rises when upstream inflation pressure is firm enough to keep inflation fears and yields elevated.",
    },
  },
  {
    slug: "core-ppi",
    title: "Core PPI",
    shortTitle: "Core PPI",
    category: "Inflation",
    description: "Cleaner upstream inflation signal excluding food and energy.",
    frequency: "monthly",
    weight: 0.07,
    scoreMode: "inflation-index",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "PPIFES",
      label: "Producer Price Index Less Foods and Energy",
      sourceLabel: "FRED / BLS",
      sourceUrl: "https://fred.stlouisfed.org/series/PPIFES",
      units: "Index",
    },
    narrative: {
      definition: "Core PPI removes food and energy to isolate persistent producer-side inflation.",
      whyItMatters: "It is useful when assessing whether inflation pressure is broadening or fading beneath volatile components.",
      inflationImpact: "Firm core PPI suggests underlying pricing power remains stronger than a benign inflation narrative would imply.",
      growthImpact: "Cost pressure can weigh on future activity if companies are unable to pass it through smoothly.",
      fedTransmission: "Sticky core producer inflation can keep the Fed biased toward restraint rather than early easing.",
      yieldDxyChain: "Firm core PPI tends to reinforce a tighter-rate narrative, which is generally constructive for DXY.",
      currentReadingLogic: "The latest value is assessed against the prior print, YoY inflation, and recent annualized trend.",
      scoringLogic: "The score rises when core pipeline inflation remains elevated enough to support a hawkish rates backdrop.",
    },
  },
  {
    slug: "nfp",
    title: "NFP",
    shortTitle: "NFP",
    category: "Growth",
    description: "Labor-market momentum through nonfarm payrolls.",
    frequency: "monthly",
    weight: 0.1,
    scoreMode: "employment-level",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "PAYEMS",
      label: "All Employees, Total Nonfarm",
      sourceLabel: "FRED / BLS",
      sourceUrl: "https://fred.stlouisfed.org/series/PAYEMS",
      units: "Thousands",
    },
    narrative: {
      definition: "NFP measures the total number of U.S. nonfarm payroll jobs.",
      whyItMatters: "Payroll growth is one of the clearest signals of whether the economy is still absorbing labor demand at a healthy pace.",
      inflationImpact: "A strong labor market can keep wage growth and services inflation sticky.",
      growthImpact: "Firm payrolls support household income, spending, and confidence in the broader growth regime.",
      fedTransmission: "As long as jobs remain resilient, the Fed has more room to stay restrictive if inflation is still above target.",
      yieldDxyChain: "Strong payroll momentum usually supports yields and the dollar by reinforcing resilience and delaying cuts.",
      currentReadingLogic: "The page tracks the latest payroll level, YoY growth, and shorter-term momentum against recent history.",
      scoringLogic: "The score rises when labor demand remains solid enough to reinforce U.S. growth and a less dovish Fed path.",
    },
  },
  {
    slug: "unemployment-rate",
    title: "Unemployment Rate",
    shortTitle: "Unemployment",
    category: "Growth",
    description: "Labor-market slack and the degree of pressure on the economy.",
    frequency: "monthly",
    weight: 0.08,
    scoreMode: "unemployment-rate",
    scoreDirection: "lower-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "UNRATE",
      label: "Civilian Unemployment Rate",
      sourceLabel: "FRED / BLS",
      sourceUrl: "https://fred.stlouisfed.org/series/UNRATE",
      units: "%",
    },
    narrative: {
      definition: "The unemployment rate captures the share of the labor force actively looking for work but currently unemployed.",
      whyItMatters: "It measures labor slack directly and strongly influences the Fed's view of labor-market balance.",
      inflationImpact: "A very low unemployment rate can keep wage pressure and service-sector inflation firmer.",
      growthImpact: "Low unemployment usually reflects resilient household income and stronger near-term demand.",
      fedTransmission: "The Fed is less likely to ease aggressively if labor slack remains limited.",
      yieldDxyChain: "A low or falling unemployment rate tends to support yields and DXY by preserving a hawkish macro backdrop.",
      currentReadingLogic: "The signal emphasizes the level, the direction versus the prior release, and the distance from recent averages.",
      scoringLogic: "The score rises when unemployment stays low and avoids a sustained upward deterioration.",
    },
  },
  {
    slug: "ism-manufacturing",
    title: "ISM Manufacturing",
    shortTitle: "ISM Mfg",
    category: "Growth",
    description: "Manufacturing cycle momentum and breadth.",
    frequency: "monthly",
    weight: 0.05,
    scoreMode: "ism-diffusion",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "ism-hybrid",
      fallbackCsvPath: "data/ism-manufacturing-history.csv",
      latestJsonPath: "data/ism-manufacturing-latest.json",
      label: "ISM Manufacturing PMI",
      sourceLabel: "ISM hybrid: local history + optional latest official adapter",
      sourceUrl: "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-pmi-reports/",
      units: "Index",
    },
    narrative: {
      definition: "ISM Manufacturing PMI is a diffusion index measuring whether factory activity is expanding or contracting.",
      whyItMatters: "It is one of the fastest monthly reads on cyclical turning points in the economy.",
      inflationImpact: "A stronger manufacturing backdrop can support pricing power and input demand, especially if inventories are lean.",
      growthImpact: "Readings above 50 usually signal expansion, while sub-50 readings point to slower industrial momentum.",
      fedTransmission: "A rebound in manufacturing reduces pressure on the Fed to deliver fast easing.",
      yieldDxyChain: "A stronger PMI can improve growth expectations, support yields, and modestly reinforce the dollar.",
      currentReadingLogic: "The signal prioritizes the level relative to 50, the last move, and the distance from recent averages.",
      scoringLogic: "The score rises when ISM is above 50 or improving toward expansion with credible momentum.",
    },
    notes: [
      "This implementation avoids brittle live scraping.",
      "If you can maintain a clean official historical CSV, the pages stay stable and extendable."
    ]
  },
  {
    slug: "ism-services",
    title: "ISM Services",
    shortTitle: "ISM Services",
    category: "Growth",
    description: "Service-sector breadth and the biggest cyclical block of the U.S. economy.",
    frequency: "monthly",
    weight: 0.06,
    scoreMode: "ism-diffusion",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "ism-hybrid",
      fallbackCsvPath: "data/ism-services-history.csv",
      latestJsonPath: "data/ism-services-latest.json",
      label: "ISM Services PMI",
      sourceLabel: "ISM hybrid: local history + optional latest official adapter",
      sourceUrl: "https://www.ismworld.org/supply-management-news-and-reports/reports/ism-pmi-reports/",
      units: "Index",
    },
    narrative: {
      definition: "ISM Services PMI measures the breadth of business conditions across the service sector.",
      whyItMatters: "Services dominate U.S. output, labor demand, and inflation persistence, so this release matters disproportionately.",
      inflationImpact: "A strong services PMI can reinforce sticky services inflation by pointing to firm demand and pricing power.",
      growthImpact: "Readings above 50 usually indicate expansion in the largest share of the economy.",
      fedTransmission: "Firm services activity can keep the Fed cautious about pivoting too early.",
      yieldDxyChain: "Resilient services activity tends to underpin yields and the dollar through a stronger growth-and-rates story.",
      currentReadingLogic: "The signal focuses on the latest print versus 50, recent trend, and relative strength versus history.",
      scoringLogic: "The score rises when services activity remains in expansion and avoids a material downshift.",
    },
    notes: [
      "This implementation favors reliability over fragile scraping.",
      "A maintained latest JSON file can be merged on top of the historical CSV when needed."
    ]
  },
  {
    slug: "umcsi",
    title: "UMCSI",
    shortTitle: "UMCSI",
    category: "Growth",
    description: "Consumer sentiment as a soft-data growth gauge.",
    frequency: "monthly",
    weight: 0.05,
    scoreMode: "sentiment-level",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "UMCSENT",
      label: "University of Michigan Consumer Sentiment",
      sourceLabel: "FRED / University of Michigan",
      sourceUrl: "https://fred.stlouisfed.org/series/UMCSENT",
      units: "Index",
    },
    narrative: {
      definition: "UMCSI tracks how households feel about current and future economic conditions.",
      whyItMatters: "Consumer sentiment is a useful soft indicator for spending appetite, recession risk, and political sensitivity to inflation.",
      inflationImpact: "Improving confidence can keep spending firm and slow the disinflation process if supply is not keeping pace.",
      growthImpact: "Healthier sentiment usually supports consumption, which remains the core engine of U.S. GDP.",
      fedTransmission: "Strong sentiment can make the Fed more comfortable staying patient if inflation is not yet fully controlled.",
      yieldDxyChain: "Better sentiment strengthens the resilience story and can indirectly support rates and DXY.",
      currentReadingLogic: "The latest reading is compared with the prior print and with recent yearly averages.",
      scoringLogic: "The score rises when sentiment improves meaningfully above depressed levels and reinforces a firmer growth regime.",
    },
  },
  {
    slug: "building-permits",
    title: "Building Permits",
    shortTitle: "Permits",
    category: "Growth",
    description: "Rate-sensitive housing activity and future construction flow.",
    frequency: "monthly",
    weight: 0.05,
    scoreMode: "housing-permits",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "PERMIT",
      label: "New Private Housing Units Authorized by Building Permits",
      sourceLabel: "FRED / U.S. Census Bureau",
      sourceUrl: "https://fred.stlouisfed.org/series/PERMIT",
      units: "Thousands of units, SAAR",
    },
    narrative: {
      definition: "Building permits track housing units authorized for construction before the physical activity arrives.",
      whyItMatters: "Housing is one of the most rate-sensitive sectors in the economy and often turns early in the cycle.",
      inflationImpact: "Housing activity can influence shelter supply and shape the medium-term inflation mix.",
      growthImpact: "Firmer permits usually suggest better residential investment and steadier cyclical demand ahead.",
      fedTransmission: "Resilient housing data can reduce the urgency for a dovish policy shift.",
      yieldDxyChain: "A stronger housing pulse helps the growth story, which can support yields and the dollar.",
      currentReadingLogic: "The signal uses the latest level, YoY growth, and recent annualized momentum against medium-term norms.",
      scoringLogic: "The score rises when permits stabilize or recover, signaling that rate-sensitive growth is not breaking down.",
    },
  },
  {
    slug: "m2-money-supply",
    title: "M2 Money Supply",
    shortTitle: "M2",
    category: "Policy",
    description: "Broad liquidity backdrop and monetary conditions.",
    frequency: "monthly",
    weight: 0.06,
    scoreMode: "money-supply",
    scoreDirection: "lower-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "M2SL",
      label: "M2 Money Stock",
      sourceLabel: "FRED / Federal Reserve",
      sourceUrl: "https://fred.stlouisfed.org/series/M2SL",
      units: "Billions of dollars",
    },
    narrative: {
      definition: "M2 is a broad measure of money and quasi-money held in the system.",
      whyItMatters: "Money-supply growth helps frame how restrictive or loose the liquidity backdrop really is.",
      inflationImpact: "Excess liquidity can support nominal demand and complicate the final stage of disinflation.",
      growthImpact: "Looser money can cushion activity, but from a DXY perspective it often coincides with softer monetary discipline.",
      fedTransmission: "If money growth is reaccelerating, the Fed has less room to assume financial conditions are tight enough.",
      yieldDxyChain: "Slower or negative M2 growth can imply tighter liquidity conditions, which is generally more supportive for DXY than abundant liquidity.",
      currentReadingLogic: "The framework emphasizes annual money growth and shorter-run direction.",
      scoringLogic: "The score rises when liquidity growth is restrained rather than rapidly reaccelerating.",
    },
  },
  {
    slug: "fed-rates",
    title: "Fed Rates",
    shortTitle: "Fed",
    category: "Policy",
    description: "The direct policy-rate anchor behind the U.S. rates regime.",
    frequency: "monthly",
    weight: 0.1,
    scoreMode: "policy-rate",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "FEDFUNDS",
      label: "Effective Federal Funds Rate",
      sourceLabel: "FRED / Federal Reserve",
      sourceUrl: "https://fred.stlouisfed.org/series/FEDFUNDS",
      units: "%",
    },
    narrative: {
      definition: "The effective federal funds rate captures the actual overnight policy setting in the money market.",
      whyItMatters: "It is the cleanest summary of how restrictive the Fed stance is right now.",
      inflationImpact: "Higher policy rates help cool demand and inflation over time.",
      growthImpact: "Restrictive policy can slow growth, but it often supports the currency through rate differentials.",
      fedTransmission: "This is the policy stance itself, so it directly expresses how much restraint the Fed is applying.",
      yieldDxyChain: "A high policy rate tends to support front-end carry and the dollar, especially when other central banks are less restrictive.",
      currentReadingLogic: "The framework compares the current level with its own history and whether the Fed is still firmly restrictive.",
      scoringLogic: "The score rises when the policy stance remains meaningfully restrictive versus recent norms.",
    },
  },
  {
    slug: "treasury-yields",
    title: "Treasury Yields",
    shortTitle: "Yields",
    category: "Market",
    description: "The rates-market transmission channel from macro to FX.",
    frequency: "daily",
    weight: 0.09,
    scoreMode: "treasury-yield",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "DGS10",
      label: "10-Year Treasury Constant Maturity Yield",
      sourceLabel: "FRED / U.S. Treasury via Federal Reserve",
      sourceUrl: "https://fred.stlouisfed.org/series/DGS10",
      units: "%",
    },
    narrative: {
      definition: "Treasury yields reflect the market's pricing of growth, inflation, policy, and term premium.",
      whyItMatters: "Yields are one of the most direct ways macro data gets transmitted into the U.S. dollar.",
      inflationImpact: "Higher yields can reflect inflation risk, tighter policy expectations, or higher real rates.",
      growthImpact: "Firm yields often accompany resilient nominal growth expectations, though excessive yield spikes can tighten conditions aggressively.",
      fedTransmission: "Treasury yields continuously price the market's expected Fed path and the credibility of the inflation regime.",
      yieldDxyChain: "Higher U.S. yields usually strengthen the dollar through better relative carry and tighter financial conditions.",
      currentReadingLogic: "The signal looks at the latest yield level, recent trend, and where yields sit relative to recent history.",
      scoringLogic: "The score rises when Treasury yields are high and holding firm enough to support the dollar backdrop.",
    },
  },
  {
    slug: "dxy",
    title: "Dollar Indexes",
    shortTitle: "Dollar",
    category: "Market",
    description: "The Federal Reserve broad-dollar macro proxy alongside a delayed market DXY quote.",
    frequency: "daily",
    weight: 0.11,
    scoreMode: "usd-broad",
    scoreDirection: "higher-is-bullish",
    primarySeries: {
      kind: "fred",
      seriesId: "DTWEXBGS",
      label: "Nominal Broad U.S. Dollar Index",
      sourceLabel: "FRED / Federal Reserve H.10",
      sourceUrl: "https://fred.stlouisfed.org/series/DTWEXBGS",
      units: "Index",
    },
    secondarySeries: {
      kind: "market-dxy-adapter",
      label: "Market DXY Adapter",
      sourceLabel: "External adapter placeholder",
      sourceUrl: "https://developer.ice.com/fixed-income-data-services/catalog/ice-data-indices-currency-indices",
      units: "Index",
    },
    narrative: {
      definition: "This page separates the official broad dollar proxy used for macro analysis from a dedicated market-style DXY adapter layer.",
      whyItMatters: "The broad dollar index is excellent for structural macro analysis, while market participants still think in terms of the tradable DXY benchmark.",
      inflationImpact: "A stronger broad dollar can help disinflation over time through the import-price channel.",
      growthImpact: "A stronger dollar can tighten financial conditions and weigh on net exports, but it often reflects macro outperformance.",
      fedTransmission: "Dollar strength feeds back into broader financial conditions and can influence how restrictive policy effectively feels.",
      yieldDxyChain: "Macro data drives Fed expectations, then yields, then the broad dollar and market DXY layer.",
      currentReadingLogic: "The official broad-dollar series is the scoring anchor, while the delayed market DXY quote is shown separately and is not treated as the same instrument.",
      scoringLogic: "The score rises when the official broad-dollar proxy is strong and trending higher versus recent history.",
    },
    notes: [
      "The broad dollar index is the official open-data macro proxy.",
      "The broad-dollar index and DXY have different baskets and levels; compare their direction, not their absolute values.",
      "A licensed feed can replace the delayed public market quote through the adapter."
    ]
  }
];

export const driverMap = Object.fromEntries(drivers.map((driver) => [driver.slug, driver]));

export const navGroups = [
  {
    label: "Overview",
    items: [
      { href: "/", label: "Home" },
      { href: "/dashboard", label: "Global DXY Dashboard" }
    ]
  },
  {
    label: "Inflation",
    items: drivers
      .filter((driver) => driver.category === "Inflation")
      .map((driver) => ({ href: `/drivers/${driver.slug}`, label: driver.shortTitle }))
  },
  {
    label: "Growth",
    items: drivers
      .filter((driver) => driver.category === "Growth")
      .map((driver) => ({ href: `/drivers/${driver.slug}`, label: driver.shortTitle }))
  },
  {
    label: "Policy & Market",
    items: drivers
      .filter((driver) => driver.category === "Policy" || driver.category === "Market")
      .map((driver) => ({ href: `/drivers/${driver.slug}`, label: driver.shortTitle }))
  },
  {
    label: "Research",
    items: [
      { href: "/snapshot", label: "Latest Snapshot" },
      { href: "/newsletter", label: "Newsletter" },
      { href: "/about", label: "About" },
      { href: "/methodology", label: "Methodology" },
      { href: "/data-sources", label: "Data Sources" }
    ]
  }
] as const;
